name: BentoBox-Level
main: world.bentobox.level.LevelPladdon
version: ${project.version}${build.number}
api-version: "1.21.4"

authors: [tastybento]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}
